---
- name: Configure repositories
  template: src=nginx.repo dest=/etc/yum.repos.d/

- name: Install nginx
  yum: name=nginx state=present


- name: copy nginx configuration for django
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf