---
- name: update yum
  shell: yum update -y

- name: Install development tools
  shell: yum -y groupinstall "Development tools"

- name: install extension lib
  yum: name={{item}} state=present
  with_items:
    - openssl-devel
    - bzip2-devel
    - expat-devel
    - gdbm-devel
    - readline-devel
    - unixODBC-devel
    - gcc-c++

- name: create directory
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /data/env
    - /data/wwwroot
    - /data/software
    - /data/repo

- name: download
  get_url: url="{{item.url}}" dest="{{item.dest}}" mode=0755
  with_items:
    - { url: "https://www.sqlite.org/2019/sqlite-{{sqlite_version}}.tar.gz",dest: "{{soft_directory}}/roles/sqlite/files/" }
    - { url: "https://www.python.org/ftp/python/{{python_version}}/Python-{{python_version}}.tgz", dest: "{{soft_directory}}/roles/python/files/" }

- name: Copy file
  template: src=sqlite_install.sh dest={{soft_directory}} mode=0777

- name: excute shell script
  shell: chdir={{soft_directory}} /bin/sh sqlite_install.sh
  register: info
  ignore_errors: true

- name: response
  debug: msg="{{ info.stdout_lines }}"
